# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import jeeves_pb2 as proto_dot_jeeves__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/jeeves_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JeevesFlowServiceStub(object):
    """============================================================================
    CodeAnalysisFlowService - Core orchestration (analysis flow)
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartFlow = channel.unary_stream(
                '/jeeves.v1.JeevesFlowService/StartFlow',
                request_serializer=proto_dot_jeeves__pb2.FlowRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.FlowEvent.FromString,
                _registered_method=True)
        self.HandleConfirmation = channel.unary_stream(
                '/jeeves.v1.JeevesFlowService/HandleConfirmation',
                request_serializer=proto_dot_jeeves__pb2.ConfirmationRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.FlowEvent.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/jeeves.v1.JeevesFlowService/CreateSession',
                request_serializer=proto_dot_jeeves__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/jeeves.v1.JeevesFlowService/GetSession',
                request_serializer=proto_dot_jeeves__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.Session.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/jeeves.v1.JeevesFlowService/ListSessions',
                request_serializer=proto_dot_jeeves__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/jeeves.v1.JeevesFlowService/DeleteSession',
                request_serializer=proto_dot_jeeves__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionMessages = channel.unary_unary(
                '/jeeves.v1.JeevesFlowService/GetSessionMessages',
                request_serializer=proto_dot_jeeves__pb2.GetSessionMessagesRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.GetSessionMessagesResponse.FromString,
                _registered_method=True)


class JeevesFlowServiceServicer(object):
    """============================================================================
    CodeAnalysisFlowService - Core orchestration (analysis flow)
    ============================================================================
    """

    def StartFlow(self, request, context):
        """Start a conversational flow, stream events back (tokens, tool calls, completion)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleConfirmation(self, request, context):
        """Handle confirmation response (yes/no/modify)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Create a new session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Get session state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List sessions for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Delete a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionMessages(self, request, context):
        """Get messages for a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JeevesFlowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartFlow': grpc.unary_stream_rpc_method_handler(
                    servicer.StartFlow,
                    request_deserializer=proto_dot_jeeves__pb2.FlowRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.FlowEvent.SerializeToString,
            ),
            'HandleConfirmation': grpc.unary_stream_rpc_method_handler(
                    servicer.HandleConfirmation,
                    request_deserializer=proto_dot_jeeves__pb2.ConfirmationRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.FlowEvent.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=proto_dot_jeeves__pb2.CreateSessionRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=proto_dot_jeeves__pb2.GetSessionRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.Session.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=proto_dot_jeeves__pb2.ListSessionsRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.ListSessionsResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=proto_dot_jeeves__pb2.DeleteSessionRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'GetSessionMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionMessages,
                    request_deserializer=proto_dot_jeeves__pb2.GetSessionMessagesRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.GetSessionMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jeeves.v1.JeevesFlowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jeeves.v1.JeevesFlowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JeevesFlowService(object):
    """============================================================================
    CodeAnalysisFlowService - Core orchestration (analysis flow)
    ============================================================================
    """

    @staticmethod
    def StartFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jeeves.v1.JeevesFlowService/StartFlow',
            proto_dot_jeeves__pb2.FlowRequest.SerializeToString,
            proto_dot_jeeves__pb2.FlowEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleConfirmation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jeeves.v1.JeevesFlowService/HandleConfirmation',
            proto_dot_jeeves__pb2.ConfirmationRequest.SerializeToString,
            proto_dot_jeeves__pb2.FlowEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.JeevesFlowService/CreateSession',
            proto_dot_jeeves__pb2.CreateSessionRequest.SerializeToString,
            proto_dot_jeeves__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.JeevesFlowService/GetSession',
            proto_dot_jeeves__pb2.GetSessionRequest.SerializeToString,
            proto_dot_jeeves__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.JeevesFlowService/ListSessions',
            proto_dot_jeeves__pb2.ListSessionsRequest.SerializeToString,
            proto_dot_jeeves__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.JeevesFlowService/DeleteSession',
            proto_dot_jeeves__pb2.DeleteSessionRequest.SerializeToString,
            proto_dot_jeeves__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.JeevesFlowService/GetSessionMessages',
            proto_dot_jeeves__pb2.GetSessionMessagesRequest.SerializeToString,
            proto_dot_jeeves__pb2.GetSessionMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GovernanceServiceStub(object):
    """============================================================================
    GovernanceService - System introspection (L7)
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealthSummary = channel.unary_unary(
                '/jeeves.v1.GovernanceService/GetHealthSummary',
                request_serializer=proto_dot_jeeves__pb2.GetHealthSummaryRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.HealthSummary.FromString,
                _registered_method=True)
        self.GetToolHealth = channel.unary_unary(
                '/jeeves.v1.GovernanceService/GetToolHealth',
                request_serializer=proto_dot_jeeves__pb2.GetToolHealthRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.ToolHealth.FromString,
                _registered_method=True)
        self.GetAgents = channel.unary_unary(
                '/jeeves.v1.GovernanceService/GetAgents',
                request_serializer=proto_dot_jeeves__pb2.GetAgentsRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.GetAgentsResponse.FromString,
                _registered_method=True)
        self.GetMemoryLayers = channel.unary_unary(
                '/jeeves.v1.GovernanceService/GetMemoryLayers',
                request_serializer=proto_dot_jeeves__pb2.GetMemoryLayersRequest.SerializeToString,
                response_deserializer=proto_dot_jeeves__pb2.GetMemoryLayersResponse.FromString,
                _registered_method=True)


class GovernanceServiceServicer(object):
    """============================================================================
    GovernanceService - System introspection (L7)
    ============================================================================
    """

    def GetHealthSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryLayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GovernanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealthSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthSummary,
                    request_deserializer=proto_dot_jeeves__pb2.GetHealthSummaryRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.HealthSummary.SerializeToString,
            ),
            'GetToolHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolHealth,
                    request_deserializer=proto_dot_jeeves__pb2.GetToolHealthRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.ToolHealth.SerializeToString,
            ),
            'GetAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgents,
                    request_deserializer=proto_dot_jeeves__pb2.GetAgentsRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.GetAgentsResponse.SerializeToString,
            ),
            'GetMemoryLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryLayers,
                    request_deserializer=proto_dot_jeeves__pb2.GetMemoryLayersRequest.FromString,
                    response_serializer=proto_dot_jeeves__pb2.GetMemoryLayersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jeeves.v1.GovernanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jeeves.v1.GovernanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GovernanceService(object):
    """============================================================================
    GovernanceService - System introspection (L7)
    ============================================================================
    """

    @staticmethod
    def GetHealthSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.GovernanceService/GetHealthSummary',
            proto_dot_jeeves__pb2.GetHealthSummaryRequest.SerializeToString,
            proto_dot_jeeves__pb2.HealthSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.GovernanceService/GetToolHealth',
            proto_dot_jeeves__pb2.GetToolHealthRequest.SerializeToString,
            proto_dot_jeeves__pb2.ToolHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.GovernanceService/GetAgents',
            proto_dot_jeeves__pb2.GetAgentsRequest.SerializeToString,
            proto_dot_jeeves__pb2.GetAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.v1.GovernanceService/GetMemoryLayers',
            proto_dot_jeeves__pb2.GetMemoryLayersRequest.SerializeToString,
            proto_dot_jeeves__pb2.GetMemoryLayersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
