"""Auto-generated Python enums from Rust source. DO NOT EDIT.

Generated by: codegen/generate_python_types.py
Source files:
  - src/envelope/enums.rs
  - src/kernel/interrupts.rs

Re-run: cd jeeves-core && python codegen/generate_python_types.py
"""

from enum import Enum


# Why processing terminated.
class TerminalReason(str, Enum):
    COMPLETED = "COMPLETED"
    MAX_ITERATIONS_EXCEEDED = "MAX_ITERATIONS_EXCEEDED"
    MAX_LLM_CALLS_EXCEEDED = "MAX_LLM_CALLS_EXCEEDED"
    MAX_AGENT_HOPS_EXCEEDED = "MAX_AGENT_HOPS_EXCEEDED"
    USER_CANCELLED = "USER_CANCELLED"
    TOOL_FAILED_FATALLY = "TOOL_FAILED_FATALLY"
    LLM_FAILED_FATALLY = "LLM_FAILED_FATALLY"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    MAX_STAGE_VISITS_EXCEEDED = "MAX_STAGE_VISITS_EXCEEDED"

# Interrupt type.
class InterruptKind(str, Enum):
    CLARIFICATION = "clarification"
    CONFIRMATION = "confirmation"
    AGENT_REVIEW = "agent_review"
    CHECKPOINT = "checkpoint"
    RESOURCE_EXHAUSTED = "resource_exhausted"
    TIMEOUT = "timeout"
    SYSTEM_ERROR = "system_error"

# Risk semantic for tool execution behavior.
class RiskSemantic(str, Enum):
    READ_ONLY = "read_only"
    WRITE = "write"
    DESTRUCTIVE = "destructive"

# Risk severity for tool execution impact.
class RiskSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

# Tool category.
class ToolCategory(str, Enum):
    READ = "read"
    WRITE = "write"
    EXECUTE = "execute"
    NETWORK = "network"
    SYSTEM = "system"
    UNIFIED = "unified"
    COMPOSITE = "composite"
    RESILIENT = "resilient"
    STANDALONE = "standalone"
    INTERNAL = "internal"

# Health status.
class HealthStatus(str, Enum):
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    UNKNOWN = "unknown"

# Loop control verdict.
class LoopVerdict(str, Enum):
    PROCEED = "proceed"
    LOOP_BACK = "loop_back"
    ADVANCE = "advance"
    ESCALATE = "escalate"

# Risk approval status.
class RiskApproval(str, Enum):
    APPROVED = "approved"
    DENIED = "denied"
    PENDING = "pending"

# Tool access level.
class ToolAccess(str, Enum):
    NONE = "none"
    READ = "read"
    WRITE = "write"
    ALL = "all"

# Operation result status.
class OperationStatus(str, Enum):
    SUCCESS = "success"
    ERROR = "error"
    NOT_FOUND = "not_found"
    TIMEOUT = "timeout"
    VALIDATION_ERROR = "validation_error"
    PARTIAL = "partial"
    INVALID_PARAMETERS = "invalid_parameters"

# Status of an interrupt.
class InterruptStatus(str, Enum):
    PENDING = "pending"
    RESOLVED = "resolved"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


__all__ = [
    "TerminalReason",
    "InterruptKind",
    "RiskSemantic",
    "RiskSeverity",
    "ToolCategory",
    "HealthStatus",
    "LoopVerdict",
    "RiskApproval",
    "ToolAccess",
    "OperationStatus",
    "InterruptStatus",
]
