// Engine gRPC Service - Python <-> Go runtime bridge
//
// This is the primary IPC mechanism between Python orchestration
// and Go execution engine. Replaces subprocess-based JSON IPC.
//
// Compile Go:
//   protoc --go_out=. --go-grpc_out=. coreengine/proto/engine.proto
//
// Compile Python:
//   python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. coreengine/proto/engine.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: coreengine/proto/engine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_CreateEnvelope_FullMethodName  = "/jeeves.engine.v1.EngineService/CreateEnvelope"
	EngineService_UpdateEnvelope_FullMethodName  = "/jeeves.engine.v1.EngineService/UpdateEnvelope"
	EngineService_CheckBounds_FullMethodName     = "/jeeves.engine.v1.EngineService/CheckBounds"
	EngineService_ExecutePipeline_FullMethodName = "/jeeves.engine.v1.EngineService/ExecutePipeline"
	EngineService_ExecuteAgent_FullMethodName    = "/jeeves.engine.v1.EngineService/ExecuteAgent"
	EngineService_CloneEnvelope_FullMethodName   = "/jeeves.engine.v1.EngineService/CloneEnvelope"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// EngineService - Go runtime operations
// =============================================================================
type EngineServiceClient interface {
	// Envelope lifecycle
	CreateEnvelope(ctx context.Context, in *CreateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error)
	UpdateEnvelope(ctx context.Context, in *UpdateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error)
	// Bounds checking (Go is authoritative)
	CheckBounds(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*BoundsResult, error)
	// Execution
	ExecutePipeline(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionEvent], error)
	ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (*AgentResult, error)
	// State management
	CloneEnvelope(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*Envelope, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) CreateEnvelope(ctx context.Context, in *CreateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, EngineService_CreateEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) UpdateEnvelope(ctx context.Context, in *UpdateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, EngineService_UpdateEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) CheckBounds(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*BoundsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoundsResult)
	err := c.cc.Invoke(ctx, EngineService_CheckBounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ExecutePipeline(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[0], EngineService_ExecutePipeline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecutionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_ExecutePipelineClient = grpc.ServerStreamingClient[ExecutionEvent]

func (c *engineServiceClient) ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (*AgentResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResult)
	err := c.cc.Invoke(ctx, EngineService_ExecuteAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) CloneEnvelope(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, EngineService_CloneEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
//
// =============================================================================
// EngineService - Go runtime operations
// =============================================================================
type EngineServiceServer interface {
	// Envelope lifecycle
	CreateEnvelope(context.Context, *CreateEnvelopeRequest) (*Envelope, error)
	UpdateEnvelope(context.Context, *UpdateEnvelopeRequest) (*Envelope, error)
	// Bounds checking (Go is authoritative)
	CheckBounds(context.Context, *Envelope) (*BoundsResult, error)
	// Execution
	ExecutePipeline(*ExecuteRequest, grpc.ServerStreamingServer[ExecutionEvent]) error
	ExecuteAgent(context.Context, *ExecuteAgentRequest) (*AgentResult, error)
	// State management
	CloneEnvelope(context.Context, *CloneRequest) (*Envelope, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) CreateEnvelope(context.Context, *CreateEnvelopeRequest) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnvelope not implemented")
}
func (UnimplementedEngineServiceServer) UpdateEnvelope(context.Context, *UpdateEnvelopeRequest) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnvelope not implemented")
}
func (UnimplementedEngineServiceServer) CheckBounds(context.Context, *Envelope) (*BoundsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBounds not implemented")
}
func (UnimplementedEngineServiceServer) ExecutePipeline(*ExecuteRequest, grpc.ServerStreamingServer[ExecutionEvent]) error {
	return status.Error(codes.Unimplemented, "method ExecutePipeline not implemented")
}
func (UnimplementedEngineServiceServer) ExecuteAgent(context.Context, *ExecuteAgentRequest) (*AgentResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAgent not implemented")
}
func (UnimplementedEngineServiceServer) CloneEnvelope(context.Context, *CloneRequest) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method CloneEnvelope not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_CreateEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CreateEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CreateEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CreateEnvelope(ctx, req.(*CreateEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_UpdateEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).UpdateEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_UpdateEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).UpdateEnvelope(ctx, req.(*UpdateEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_CheckBounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CheckBounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CheckBounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CheckBounds(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ExecutePipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).ExecutePipeline(m, &grpc.GenericServerStream[ExecuteRequest, ExecutionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_ExecutePipelineServer = grpc.ServerStreamingServer[ExecutionEvent]

func _EngineService_ExecuteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ExecuteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ExecuteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ExecuteAgent(ctx, req.(*ExecuteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_CloneEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CloneEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CloneEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CloneEnvelope(ctx, req.(*CloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jeeves.engine.v1.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEnvelope",
			Handler:    _EngineService_CreateEnvelope_Handler,
		},
		{
			MethodName: "UpdateEnvelope",
			Handler:    _EngineService_UpdateEnvelope_Handler,
		},
		{
			MethodName: "CheckBounds",
			Handler:    _EngineService_CheckBounds_Handler,
		},
		{
			MethodName: "ExecuteAgent",
			Handler:    _EngineService_ExecuteAgent_Handler,
		},
		{
			MethodName: "CloneEnvelope",
			Handler:    _EngineService_CloneEnvelope_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecutePipeline",
			Handler:       _EngineService_ExecutePipeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "coreengine/proto/engine.proto",
}
