// Engine gRPC Service - Python <-> Go runtime bridge
//
// This is the primary IPC mechanism between Python orchestration
// and Go execution engine. Replaces subprocess-based JSON IPC.
//
// Compile Go:
//   protoc --go_out=. --go-grpc_out=. coreengine/proto/engine.proto
//
// Compile Python:
//   python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. coreengine/proto/engine.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: coreengine/proto/engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminalReason int32

const (
	TerminalReason_TERMINAL_REASON_UNSPECIFIED TerminalReason = 0
	TerminalReason_MAX_ITERATIONS_EXCEEDED     TerminalReason = 1
	TerminalReason_MAX_LLM_CALLS_EXCEEDED      TerminalReason = 2
	TerminalReason_MAX_AGENT_HOPS_EXCEEDED     TerminalReason = 3
	TerminalReason_USER_CANCELLED              TerminalReason = 4
	TerminalReason_TOOL_FAILED_FATALLY         TerminalReason = 5
	TerminalReason_LLM_FAILED_FATALLY          TerminalReason = 6
	TerminalReason_COMPLETED                   TerminalReason = 7
)

// Enum value maps for TerminalReason.
var (
	TerminalReason_name = map[int32]string{
		0: "TERMINAL_REASON_UNSPECIFIED",
		1: "MAX_ITERATIONS_EXCEEDED",
		2: "MAX_LLM_CALLS_EXCEEDED",
		3: "MAX_AGENT_HOPS_EXCEEDED",
		4: "USER_CANCELLED",
		5: "TOOL_FAILED_FATALLY",
		6: "LLM_FAILED_FATALLY",
		7: "COMPLETED",
	}
	TerminalReason_value = map[string]int32{
		"TERMINAL_REASON_UNSPECIFIED": 0,
		"MAX_ITERATIONS_EXCEEDED":     1,
		"MAX_LLM_CALLS_EXCEEDED":      2,
		"MAX_AGENT_HOPS_EXCEEDED":     3,
		"USER_CANCELLED":              4,
		"TOOL_FAILED_FATALLY":         5,
		"LLM_FAILED_FATALLY":          6,
		"COMPLETED":                   7,
	}
)

func (x TerminalReason) Enum() *TerminalReason {
	p := new(TerminalReason)
	*p = x
	return p
}

func (x TerminalReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalReason) Descriptor() protoreflect.EnumDescriptor {
	return file_coreengine_proto_engine_proto_enumTypes[0].Descriptor()
}

func (TerminalReason) Type() protoreflect.EnumType {
	return &file_coreengine_proto_engine_proto_enumTypes[0]
}

func (x TerminalReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalReason.Descriptor instead.
func (TerminalReason) EnumDescriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{0}
}

type InterruptKind int32

const (
	InterruptKind_INTERRUPT_KIND_UNSPECIFIED InterruptKind = 0
	InterruptKind_CLARIFICATION              InterruptKind = 1
	InterruptKind_CONFIRMATION               InterruptKind = 2
	InterruptKind_CHECKPOINT                 InterruptKind = 3
	InterruptKind_RESOURCE_EXHAUSTED         InterruptKind = 4
	InterruptKind_TIMEOUT                    InterruptKind = 5
	InterruptKind_SYSTEM_ERROR               InterruptKind = 6
	InterruptKind_AGENT_REVIEW               InterruptKind = 7
)

// Enum value maps for InterruptKind.
var (
	InterruptKind_name = map[int32]string{
		0: "INTERRUPT_KIND_UNSPECIFIED",
		1: "CLARIFICATION",
		2: "CONFIRMATION",
		3: "CHECKPOINT",
		4: "RESOURCE_EXHAUSTED",
		5: "TIMEOUT",
		6: "SYSTEM_ERROR",
		7: "AGENT_REVIEW",
	}
	InterruptKind_value = map[string]int32{
		"INTERRUPT_KIND_UNSPECIFIED": 0,
		"CLARIFICATION":              1,
		"CONFIRMATION":               2,
		"CHECKPOINT":                 3,
		"RESOURCE_EXHAUSTED":         4,
		"TIMEOUT":                    5,
		"SYSTEM_ERROR":               6,
		"AGENT_REVIEW":               7,
	}
)

func (x InterruptKind) Enum() *InterruptKind {
	p := new(InterruptKind)
	*p = x
	return p
}

func (x InterruptKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterruptKind) Descriptor() protoreflect.EnumDescriptor {
	return file_coreengine_proto_engine_proto_enumTypes[1].Descriptor()
}

func (InterruptKind) Type() protoreflect.EnumType {
	return &file_coreengine_proto_engine_proto_enumTypes[1]
}

func (x InterruptKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterruptKind.Descriptor instead.
func (InterruptKind) EnumDescriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{1}
}

type ExecutionEventType int32

const (
	ExecutionEventType_EXECUTION_EVENT_TYPE_UNSPECIFIED ExecutionEventType = 0
	ExecutionEventType_STAGE_STARTED                    ExecutionEventType = 1
	ExecutionEventType_STAGE_COMPLETED                  ExecutionEventType = 2
	ExecutionEventType_STAGE_FAILED                     ExecutionEventType = 3
	ExecutionEventType_PIPELINE_COMPLETED               ExecutionEventType = 4
	ExecutionEventType_INTERRUPT_RAISED                 ExecutionEventType = 5
	ExecutionEventType_CHECKPOINT_CREATED               ExecutionEventType = 6
	ExecutionEventType_BOUNDS_EXCEEDED                  ExecutionEventType = 7
)

// Enum value maps for ExecutionEventType.
var (
	ExecutionEventType_name = map[int32]string{
		0: "EXECUTION_EVENT_TYPE_UNSPECIFIED",
		1: "STAGE_STARTED",
		2: "STAGE_COMPLETED",
		3: "STAGE_FAILED",
		4: "PIPELINE_COMPLETED",
		5: "INTERRUPT_RAISED",
		6: "CHECKPOINT_CREATED",
		7: "BOUNDS_EXCEEDED",
	}
	ExecutionEventType_value = map[string]int32{
		"EXECUTION_EVENT_TYPE_UNSPECIFIED": 0,
		"STAGE_STARTED":                    1,
		"STAGE_COMPLETED":                  2,
		"STAGE_FAILED":                     3,
		"PIPELINE_COMPLETED":               4,
		"INTERRUPT_RAISED":                 5,
		"CHECKPOINT_CREATED":               6,
		"BOUNDS_EXCEEDED":                  7,
	}
)

func (x ExecutionEventType) Enum() *ExecutionEventType {
	p := new(ExecutionEventType)
	*p = x
	return p
}

func (x ExecutionEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_coreengine_proto_engine_proto_enumTypes[2].Descriptor()
}

func (ExecutionEventType) Type() protoreflect.EnumType {
	return &file_coreengine_proto_engine_proto_enumTypes[2]
}

func (x ExecutionEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionEventType.Descriptor instead.
func (ExecutionEventType) EnumDescriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{2}
}

type CreateEnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawInput      string                 `protobuf:"bytes,1,opt,name=raw_input,json=rawInput,proto3" json:"raw_input,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Optional, generated if empty
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StageOrder    []string               `protobuf:"bytes,6,rep,name=stage_order,json=stageOrder,proto3" json:"stage_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvelopeRequest) Reset() {
	*x = CreateEnvelopeRequest{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvelopeRequest) ProtoMessage() {}

func (x *CreateEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEnvelopeRequest) GetRawInput() string {
	if x != nil {
		return x.RawInput
	}
	return ""
}

func (x *CreateEnvelopeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEnvelopeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateEnvelopeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateEnvelopeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateEnvelopeRequest) GetStageOrder() []string {
	if x != nil {
		return x.StageOrder
	}
	return nil
}

type UpdateEnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnvelopeRequest) Reset() {
	*x = UpdateEnvelopeRequest{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvelopeRequest) ProtoMessage() {}

func (x *UpdateEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateEnvelopeRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type CloneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{2}
}

func (x *CloneRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	EnvelopeId string `protobuf:"bytes,1,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	RequestId  string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId     string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId  string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Input
	RawInput     string `protobuf:"bytes,5,opt,name=raw_input,json=rawInput,proto3" json:"raw_input,omitempty"`
	ReceivedAtMs int64  `protobuf:"varint,6,opt,name=received_at_ms,json=receivedAtMs,proto3" json:"received_at_ms,omitempty"`
	// Pipeline state
	CurrentStage  string   `protobuf:"bytes,7,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`
	StageOrder    []string `protobuf:"bytes,8,rep,name=stage_order,json=stageOrder,proto3" json:"stage_order,omitempty"`
	Iteration     int32    `protobuf:"varint,9,opt,name=iteration,proto3" json:"iteration,omitempty"`
	MaxIterations int32    `protobuf:"varint,10,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	// Bounds
	LlmCallCount  int32 `protobuf:"varint,11,opt,name=llm_call_count,json=llmCallCount,proto3" json:"llm_call_count,omitempty"`
	MaxLlmCalls   int32 `protobuf:"varint,12,opt,name=max_llm_calls,json=maxLlmCalls,proto3" json:"max_llm_calls,omitempty"`
	AgentHopCount int32 `protobuf:"varint,13,opt,name=agent_hop_count,json=agentHopCount,proto3" json:"agent_hop_count,omitempty"`
	MaxAgentHops  int32 `protobuf:"varint,14,opt,name=max_agent_hops,json=maxAgentHops,proto3" json:"max_agent_hops,omitempty"`
	// Termination
	Terminated        bool           `protobuf:"varint,15,opt,name=terminated,proto3" json:"terminated,omitempty"`
	TerminationReason string         `protobuf:"bytes,16,opt,name=termination_reason,json=terminationReason,proto3" json:"termination_reason,omitempty"`
	TerminalReason    TerminalReason `protobuf:"varint,17,opt,name=terminal_reason,json=terminalReason,proto3,enum=jeeves.engine.v1.TerminalReason" json:"terminal_reason,omitempty"`
	CompletedAtMs     int64          `protobuf:"varint,18,opt,name=completed_at_ms,json=completedAtMs,proto3" json:"completed_at_ms,omitempty"`
	// Interrupt
	InterruptPending bool           `protobuf:"varint,19,opt,name=interrupt_pending,json=interruptPending,proto3" json:"interrupt_pending,omitempty"`
	Interrupt        *FlowInterrupt `protobuf:"bytes,20,opt,name=interrupt,proto3" json:"interrupt,omitempty"`
	// Outputs (JSON-encoded per-agent outputs)
	Outputs map[string][]byte `protobuf:"bytes,21,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Parallel execution state
	ActiveStages      map[string]bool   `protobuf:"bytes,22,rep,name=active_stages,json=activeStages,proto3" json:"active_stages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CompletedStageSet map[string]bool   `protobuf:"bytes,23,rep,name=completed_stage_set,json=completedStageSet,proto3" json:"completed_stage_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FailedStages      map[string]string `protobuf:"bytes,24,rep,name=failed_stages,json=failedStages,proto3" json:"failed_stages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Multi-stage
	CurrentStageNumber int32 `protobuf:"varint,25,opt,name=current_stage_number,json=currentStageNumber,proto3" json:"current_stage_number,omitempty"`
	MaxStages          int32 `protobuf:"varint,26,opt,name=max_stages,json=maxStages,proto3" json:"max_stages,omitempty"`
	// Goals
	AllGoals             []string          `protobuf:"bytes,27,rep,name=all_goals,json=allGoals,proto3" json:"all_goals,omitempty"`
	RemainingGoals       []string          `protobuf:"bytes,28,rep,name=remaining_goals,json=remainingGoals,proto3" json:"remaining_goals,omitempty"`
	GoalCompletionStatus map[string]string `protobuf:"bytes,29,rep,name=goal_completion_status,json=goalCompletionStatus,proto3" json:"goal_completion_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metadata
	MetadataStr   map[string]string `protobuf:"bytes,30,rep,name=metadata_str,json=metadataStr,proto3" json:"metadata_str,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAtMs   int64             `protobuf:"varint,31,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetRawInput() string {
	if x != nil {
		return x.RawInput
	}
	return ""
}

func (x *Envelope) GetReceivedAtMs() int64 {
	if x != nil {
		return x.ReceivedAtMs
	}
	return 0
}

func (x *Envelope) GetCurrentStage() string {
	if x != nil {
		return x.CurrentStage
	}
	return ""
}

func (x *Envelope) GetStageOrder() []string {
	if x != nil {
		return x.StageOrder
	}
	return nil
}

func (x *Envelope) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *Envelope) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *Envelope) GetLlmCallCount() int32 {
	if x != nil {
		return x.LlmCallCount
	}
	return 0
}

func (x *Envelope) GetMaxLlmCalls() int32 {
	if x != nil {
		return x.MaxLlmCalls
	}
	return 0
}

func (x *Envelope) GetAgentHopCount() int32 {
	if x != nil {
		return x.AgentHopCount
	}
	return 0
}

func (x *Envelope) GetMaxAgentHops() int32 {
	if x != nil {
		return x.MaxAgentHops
	}
	return 0
}

func (x *Envelope) GetTerminated() bool {
	if x != nil {
		return x.Terminated
	}
	return false
}

func (x *Envelope) GetTerminationReason() string {
	if x != nil {
		return x.TerminationReason
	}
	return ""
}

func (x *Envelope) GetTerminalReason() TerminalReason {
	if x != nil {
		return x.TerminalReason
	}
	return TerminalReason_TERMINAL_REASON_UNSPECIFIED
}

func (x *Envelope) GetCompletedAtMs() int64 {
	if x != nil {
		return x.CompletedAtMs
	}
	return 0
}

func (x *Envelope) GetInterruptPending() bool {
	if x != nil {
		return x.InterruptPending
	}
	return false
}

func (x *Envelope) GetInterrupt() *FlowInterrupt {
	if x != nil {
		return x.Interrupt
	}
	return nil
}

func (x *Envelope) GetOutputs() map[string][]byte {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Envelope) GetActiveStages() map[string]bool {
	if x != nil {
		return x.ActiveStages
	}
	return nil
}

func (x *Envelope) GetCompletedStageSet() map[string]bool {
	if x != nil {
		return x.CompletedStageSet
	}
	return nil
}

func (x *Envelope) GetFailedStages() map[string]string {
	if x != nil {
		return x.FailedStages
	}
	return nil
}

func (x *Envelope) GetCurrentStageNumber() int32 {
	if x != nil {
		return x.CurrentStageNumber
	}
	return 0
}

func (x *Envelope) GetMaxStages() int32 {
	if x != nil {
		return x.MaxStages
	}
	return 0
}

func (x *Envelope) GetAllGoals() []string {
	if x != nil {
		return x.AllGoals
	}
	return nil
}

func (x *Envelope) GetRemainingGoals() []string {
	if x != nil {
		return x.RemainingGoals
	}
	return nil
}

func (x *Envelope) GetGoalCompletionStatus() map[string]string {
	if x != nil {
		return x.GoalCompletionStatus
	}
	return nil
}

func (x *Envelope) GetMetadataStr() map[string]string {
	if x != nil {
		return x.MetadataStr
	}
	return nil
}

func (x *Envelope) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

type FlowInterrupt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          InterruptKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=jeeves.engine.v1.InterruptKind" json:"kind,omitempty"`
	InterruptId   string                 `protobuf:"bytes,2,opt,name=interrupt_id,json=interruptId,proto3" json:"interrupt_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded additional data
	Response      *InterruptResponse     `protobuf:"bytes,6,opt,name=response,proto3" json:"response,omitempty"`
	CreatedAtMs   int64                  `protobuf:"varint,7,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowInterrupt) Reset() {
	*x = FlowInterrupt{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowInterrupt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowInterrupt) ProtoMessage() {}

func (x *FlowInterrupt) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowInterrupt.ProtoReflect.Descriptor instead.
func (*FlowInterrupt) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{4}
}

func (x *FlowInterrupt) GetKind() InterruptKind {
	if x != nil {
		return x.Kind
	}
	return InterruptKind_INTERRUPT_KIND_UNSPECIFIED
}

func (x *FlowInterrupt) GetInterruptId() string {
	if x != nil {
		return x.InterruptId
	}
	return ""
}

func (x *FlowInterrupt) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *FlowInterrupt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FlowInterrupt) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FlowInterrupt) GetResponse() *InterruptResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FlowInterrupt) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

type InterruptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded response data
	ResolvedAtMs  int64                  `protobuf:"varint,5,opt,name=resolved_at_ms,json=resolvedAtMs,proto3" json:"resolved_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptResponse) Reset() {
	*x = InterruptResponse{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptResponse) ProtoMessage() {}

func (x *InterruptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptResponse.ProtoReflect.Descriptor instead.
func (*InterruptResponse) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{5}
}

func (x *InterruptResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InterruptResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *InterruptResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *InterruptResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InterruptResponse) GetResolvedAtMs() int64 {
	if x != nil {
		return x.ResolvedAtMs
	}
	return 0
}

type BoundsResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CanContinue         bool                   `protobuf:"varint,1,opt,name=can_continue,json=canContinue,proto3" json:"can_continue,omitempty"`
	TerminalReason      TerminalReason         `protobuf:"varint,2,opt,name=terminal_reason,json=terminalReason,proto3,enum=jeeves.engine.v1.TerminalReason" json:"terminal_reason,omitempty"`
	LlmCallsRemaining   int32                  `protobuf:"varint,3,opt,name=llm_calls_remaining,json=llmCallsRemaining,proto3" json:"llm_calls_remaining,omitempty"`
	AgentHopsRemaining  int32                  `protobuf:"varint,4,opt,name=agent_hops_remaining,json=agentHopsRemaining,proto3" json:"agent_hops_remaining,omitempty"`
	IterationsRemaining int32                  `protobuf:"varint,5,opt,name=iterations_remaining,json=iterationsRemaining,proto3" json:"iterations_remaining,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BoundsResult) Reset() {
	*x = BoundsResult{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundsResult) ProtoMessage() {}

func (x *BoundsResult) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundsResult.ProtoReflect.Descriptor instead.
func (*BoundsResult) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{6}
}

func (x *BoundsResult) GetCanContinue() bool {
	if x != nil {
		return x.CanContinue
	}
	return false
}

func (x *BoundsResult) GetTerminalReason() TerminalReason {
	if x != nil {
		return x.TerminalReason
	}
	return TerminalReason_TERMINAL_REASON_UNSPECIFIED
}

func (x *BoundsResult) GetLlmCallsRemaining() int32 {
	if x != nil {
		return x.LlmCallsRemaining
	}
	return 0
}

func (x *BoundsResult) GetAgentHopsRemaining() int32 {
	if x != nil {
		return x.AgentHopsRemaining
	}
	return 0
}

func (x *BoundsResult) GetIterationsRemaining() int32 {
	if x != nil {
		return x.IterationsRemaining
	}
	return 0
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Envelope       *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ThreadId       string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	PipelineConfig []byte                 `protobuf:"bytes,3,opt,name=pipeline_config,json=pipelineConfig,proto3" json:"pipeline_config,omitempty"` // JSON-encoded PipelineConfig
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *ExecuteRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ExecuteRequest) GetPipelineConfig() []byte {
	if x != nil {
		return x.PipelineConfig
	}
	return nil
}

type ExecuteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentConfig   []byte                 `protobuf:"bytes,3,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"` // JSON-encoded AgentConfig
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteAgentRequest) Reset() {
	*x = ExecuteAgentRequest{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAgentRequest) ProtoMessage() {}

func (x *ExecuteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAgentRequest.ProtoReflect.Descriptor instead.
func (*ExecuteAgentRequest) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteAgentRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *ExecuteAgentRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *ExecuteAgentRequest) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ExecutionEventType     `protobuf:"varint,1,opt,name=type,proto3,enum=jeeves.engine.v1.ExecutionEventType" json:"type,omitempty"`
	Stage         string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`   // JSON-encoded event data
	Envelope      *Envelope              `protobuf:"bytes,5,opt,name=envelope,proto3" json:"envelope,omitempty"` // Updated envelope after event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutionEvent) GetType() ExecutionEventType {
	if x != nil {
		return x.Type
	}
	return ExecutionEventType_EXECUTION_EVENT_TYPE_UNSPECIFIED
}

func (x *ExecutionEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ExecutionEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ExecutionEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutionEvent) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type AgentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // JSON-encoded output
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	LlmCalls      int32                  `protobuf:"varint,5,opt,name=llm_calls,json=llmCalls,proto3" json:"llm_calls,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,6,opt,name=envelope,proto3" json:"envelope,omitempty"` // Updated envelope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResult) Reset() {
	*x = AgentResult{}
	mi := &file_coreengine_proto_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResult) ProtoMessage() {}

func (x *AgentResult) ProtoReflect() protoreflect.Message {
	mi := &file_coreengine_proto_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResult.ProtoReflect.Descriptor instead.
func (*AgentResult) Descriptor() ([]byte, []int) {
	return file_coreengine_proto_engine_proto_rawDescGZIP(), []int{10}
}

func (x *AgentResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *AgentResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentResult) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AgentResult) GetLlmCalls() int32 {
	if x != nil {
		return x.LlmCalls
	}
	return 0
}

func (x *AgentResult) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

var File_coreengine_proto_engine_proto protoreflect.FileDescriptor

const file_coreengine_proto_engine_proto_rawDesc = "" +
	"\n" +
	"\x1dcoreengine/proto/engine.proto\x12\x10jeeves.engine.v1\"\xbc\x02\n" +
	"\x15CreateEnvelopeRequest\x12\x1b\n" +
	"\traw_input\x18\x01 \x01(\tR\brawInput\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12Q\n" +
	"\bmetadata\x18\x05 \x03(\v25.jeeves.engine.v1.CreateEnvelopeRequest.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vstage_order\x18\x06 \x03(\tR\n" +
	"stageOrder\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x15UpdateEnvelopeRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.jeeves.engine.v1.EnvelopeR\benvelope\"F\n" +
	"\fCloneRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.jeeves.engine.v1.EnvelopeR\benvelope\"\xe6\x0e\n" +
	"\bEnvelope\x12\x1f\n" +
	"\venvelope_id\x18\x01 \x01(\tR\n" +
	"envelopeId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1b\n" +
	"\traw_input\x18\x05 \x01(\tR\brawInput\x12$\n" +
	"\x0ereceived_at_ms\x18\x06 \x01(\x03R\freceivedAtMs\x12#\n" +
	"\rcurrent_stage\x18\a \x01(\tR\fcurrentStage\x12\x1f\n" +
	"\vstage_order\x18\b \x03(\tR\n" +
	"stageOrder\x12\x1c\n" +
	"\titeration\x18\t \x01(\x05R\titeration\x12%\n" +
	"\x0emax_iterations\x18\n" +
	" \x01(\x05R\rmaxIterations\x12$\n" +
	"\x0ellm_call_count\x18\v \x01(\x05R\fllmCallCount\x12\"\n" +
	"\rmax_llm_calls\x18\f \x01(\x05R\vmaxLlmCalls\x12&\n" +
	"\x0fagent_hop_count\x18\r \x01(\x05R\ragentHopCount\x12$\n" +
	"\x0emax_agent_hops\x18\x0e \x01(\x05R\fmaxAgentHops\x12\x1e\n" +
	"\n" +
	"terminated\x18\x0f \x01(\bR\n" +
	"terminated\x12-\n" +
	"\x12termination_reason\x18\x10 \x01(\tR\x11terminationReason\x12I\n" +
	"\x0fterminal_reason\x18\x11 \x01(\x0e2 .jeeves.engine.v1.TerminalReasonR\x0eterminalReason\x12&\n" +
	"\x0fcompleted_at_ms\x18\x12 \x01(\x03R\rcompletedAtMs\x12+\n" +
	"\x11interrupt_pending\x18\x13 \x01(\bR\x10interruptPending\x12=\n" +
	"\tinterrupt\x18\x14 \x01(\v2\x1f.jeeves.engine.v1.FlowInterruptR\tinterrupt\x12A\n" +
	"\aoutputs\x18\x15 \x03(\v2'.jeeves.engine.v1.Envelope.OutputsEntryR\aoutputs\x12Q\n" +
	"\ractive_stages\x18\x16 \x03(\v2,.jeeves.engine.v1.Envelope.ActiveStagesEntryR\factiveStages\x12a\n" +
	"\x13completed_stage_set\x18\x17 \x03(\v21.jeeves.engine.v1.Envelope.CompletedStageSetEntryR\x11completedStageSet\x12Q\n" +
	"\rfailed_stages\x18\x18 \x03(\v2,.jeeves.engine.v1.Envelope.FailedStagesEntryR\ffailedStages\x120\n" +
	"\x14current_stage_number\x18\x19 \x01(\x05R\x12currentStageNumber\x12\x1d\n" +
	"\n" +
	"max_stages\x18\x1a \x01(\x05R\tmaxStages\x12\x1b\n" +
	"\tall_goals\x18\x1b \x03(\tR\ballGoals\x12'\n" +
	"\x0fremaining_goals\x18\x1c \x03(\tR\x0eremainingGoals\x12j\n" +
	"\x16goal_completion_status\x18\x1d \x03(\v24.jeeves.engine.v1.Envelope.GoalCompletionStatusEntryR\x14goalCompletionStatus\x12N\n" +
	"\fmetadata_str\x18\x1e \x03(\v2+.jeeves.engine.v1.Envelope.MetadataStrEntryR\vmetadataStr\x12\"\n" +
	"\rcreated_at_ms\x18\x1f \x01(\x03R\vcreatedAtMs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a?\n" +
	"\x11ActiveStagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aD\n" +
	"\x16CompletedStageSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a?\n" +
	"\x11FailedStagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19GoalCompletionStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10MetadataStrEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x02\n" +
	"\rFlowInterrupt\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.jeeves.engine.v1.InterruptKindR\x04kind\x12!\n" +
	"\finterrupt_id\x18\x02 \x01(\tR\vinterruptId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12?\n" +
	"\bresponse\x18\x06 \x01(\v2#.jeeves.engine.v1.InterruptResponseR\bresponse\x12\"\n" +
	"\rcreated_at_ms\x18\a \x01(\x03R\vcreatedAtMs\"\x99\x01\n" +
	"\x11InterruptResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12$\n" +
	"\x0eresolved_at_ms\x18\x05 \x01(\x03R\fresolvedAtMs\"\x91\x02\n" +
	"\fBoundsResult\x12!\n" +
	"\fcan_continue\x18\x01 \x01(\bR\vcanContinue\x12I\n" +
	"\x0fterminal_reason\x18\x02 \x01(\x0e2 .jeeves.engine.v1.TerminalReasonR\x0eterminalReason\x12.\n" +
	"\x13llm_calls_remaining\x18\x03 \x01(\x05R\x11llmCallsRemaining\x120\n" +
	"\x14agent_hops_remaining\x18\x04 \x01(\x05R\x12agentHopsRemaining\x121\n" +
	"\x14iterations_remaining\x18\x05 \x01(\x05R\x13iterationsRemaining\"\x8e\x01\n" +
	"\x0eExecuteRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.jeeves.engine.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12'\n" +
	"\x0fpipeline_config\x18\x03 \x01(\fR\x0epipelineConfig\"\x8f\x01\n" +
	"\x13ExecuteAgentRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.jeeves.engine.v1.EnvelopeR\benvelope\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12!\n" +
	"\fagent_config\x18\x03 \x01(\fR\vagentConfig\"\xd5\x01\n" +
	"\x0eExecutionEvent\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.jeeves.engine.v1.ExecutionEventTypeR\x04type\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x126\n" +
	"\benvelope\x18\x05 \x01(\v2\x1a.jeeves.engine.v1.EnvelopeR\benvelope\"\xcb\x01\n" +
	"\vAgentResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\x12\x1b\n" +
	"\tllm_calls\x18\x05 \x01(\x05R\bllmCalls\x126\n" +
	"\benvelope\x18\x06 \x01(\v2\x1a.jeeves.engine.v1.EnvelopeR\benvelope*\xdb\x01\n" +
	"\x0eTerminalReason\x12\x1f\n" +
	"\x1bTERMINAL_REASON_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MAX_ITERATIONS_EXCEEDED\x10\x01\x12\x1a\n" +
	"\x16MAX_LLM_CALLS_EXCEEDED\x10\x02\x12\x1b\n" +
	"\x17MAX_AGENT_HOPS_EXCEEDED\x10\x03\x12\x12\n" +
	"\x0eUSER_CANCELLED\x10\x04\x12\x17\n" +
	"\x13TOOL_FAILED_FATALLY\x10\x05\x12\x16\n" +
	"\x12LLM_FAILED_FATALLY\x10\x06\x12\r\n" +
	"\tCOMPLETED\x10\a*\xad\x01\n" +
	"\rInterruptKind\x12\x1e\n" +
	"\x1aINTERRUPT_KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCLARIFICATION\x10\x01\x12\x10\n" +
	"\fCONFIRMATION\x10\x02\x12\x0e\n" +
	"\n" +
	"CHECKPOINT\x10\x03\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\x04\x12\v\n" +
	"\aTIMEOUT\x10\x05\x12\x10\n" +
	"\fSYSTEM_ERROR\x10\x06\x12\x10\n" +
	"\fAGENT_REVIEW\x10\a*\xcf\x01\n" +
	"\x12ExecutionEventType\x12$\n" +
	" EXECUTION_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTAGE_STARTED\x10\x01\x12\x13\n" +
	"\x0fSTAGE_COMPLETED\x10\x02\x12\x10\n" +
	"\fSTAGE_FAILED\x10\x03\x12\x16\n" +
	"\x12PIPELINE_COMPLETED\x10\x04\x12\x14\n" +
	"\x10INTERRUPT_RAISED\x10\x05\x12\x16\n" +
	"\x12CHECKPOINT_CREATED\x10\x06\x12\x13\n" +
	"\x0fBOUNDS_EXCEEDED\x10\a2\x84\x04\n" +
	"\rEngineService\x12U\n" +
	"\x0eCreateEnvelope\x12'.jeeves.engine.v1.CreateEnvelopeRequest\x1a\x1a.jeeves.engine.v1.Envelope\x12U\n" +
	"\x0eUpdateEnvelope\x12'.jeeves.engine.v1.UpdateEnvelopeRequest\x1a\x1a.jeeves.engine.v1.Envelope\x12I\n" +
	"\vCheckBounds\x12\x1a.jeeves.engine.v1.Envelope\x1a\x1e.jeeves.engine.v1.BoundsResult\x12W\n" +
	"\x0fExecutePipeline\x12 .jeeves.engine.v1.ExecuteRequest\x1a .jeeves.engine.v1.ExecutionEvent0\x01\x12T\n" +
	"\fExecuteAgent\x12%.jeeves.engine.v1.ExecuteAgentRequest\x1a\x1d.jeeves.engine.v1.AgentResult\x12K\n" +
	"\rCloneEnvelope\x12\x1e.jeeves.engine.v1.CloneRequest\x1a\x1a.jeeves.engine.v1.EnvelopeBFZDgithub.com/jeeves-cluster-organization/codeanalysis/coreengine/protob\x06proto3"

var (
	file_coreengine_proto_engine_proto_rawDescOnce sync.Once
	file_coreengine_proto_engine_proto_rawDescData []byte
)

func file_coreengine_proto_engine_proto_rawDescGZIP() []byte {
	file_coreengine_proto_engine_proto_rawDescOnce.Do(func() {
		file_coreengine_proto_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coreengine_proto_engine_proto_rawDesc), len(file_coreengine_proto_engine_proto_rawDesc)))
	})
	return file_coreengine_proto_engine_proto_rawDescData
}

var file_coreengine_proto_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_coreengine_proto_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_coreengine_proto_engine_proto_goTypes = []any{
	(TerminalReason)(0),           // 0: jeeves.engine.v1.TerminalReason
	(InterruptKind)(0),            // 1: jeeves.engine.v1.InterruptKind
	(ExecutionEventType)(0),       // 2: jeeves.engine.v1.ExecutionEventType
	(*CreateEnvelopeRequest)(nil), // 3: jeeves.engine.v1.CreateEnvelopeRequest
	(*UpdateEnvelopeRequest)(nil), // 4: jeeves.engine.v1.UpdateEnvelopeRequest
	(*CloneRequest)(nil),          // 5: jeeves.engine.v1.CloneRequest
	(*Envelope)(nil),              // 6: jeeves.engine.v1.Envelope
	(*FlowInterrupt)(nil),         // 7: jeeves.engine.v1.FlowInterrupt
	(*InterruptResponse)(nil),     // 8: jeeves.engine.v1.InterruptResponse
	(*BoundsResult)(nil),          // 9: jeeves.engine.v1.BoundsResult
	(*ExecuteRequest)(nil),        // 10: jeeves.engine.v1.ExecuteRequest
	(*ExecuteAgentRequest)(nil),   // 11: jeeves.engine.v1.ExecuteAgentRequest
	(*ExecutionEvent)(nil),        // 12: jeeves.engine.v1.ExecutionEvent
	(*AgentResult)(nil),           // 13: jeeves.engine.v1.AgentResult
	nil,                           // 14: jeeves.engine.v1.CreateEnvelopeRequest.MetadataEntry
	nil,                           // 15: jeeves.engine.v1.Envelope.OutputsEntry
	nil,                           // 16: jeeves.engine.v1.Envelope.ActiveStagesEntry
	nil,                           // 17: jeeves.engine.v1.Envelope.CompletedStageSetEntry
	nil,                           // 18: jeeves.engine.v1.Envelope.FailedStagesEntry
	nil,                           // 19: jeeves.engine.v1.Envelope.GoalCompletionStatusEntry
	nil,                           // 20: jeeves.engine.v1.Envelope.MetadataStrEntry
}
var file_coreengine_proto_engine_proto_depIdxs = []int32{
	14, // 0: jeeves.engine.v1.CreateEnvelopeRequest.metadata:type_name -> jeeves.engine.v1.CreateEnvelopeRequest.MetadataEntry
	6,  // 1: jeeves.engine.v1.UpdateEnvelopeRequest.envelope:type_name -> jeeves.engine.v1.Envelope
	6,  // 2: jeeves.engine.v1.CloneRequest.envelope:type_name -> jeeves.engine.v1.Envelope
	0,  // 3: jeeves.engine.v1.Envelope.terminal_reason:type_name -> jeeves.engine.v1.TerminalReason
	7,  // 4: jeeves.engine.v1.Envelope.interrupt:type_name -> jeeves.engine.v1.FlowInterrupt
	15, // 5: jeeves.engine.v1.Envelope.outputs:type_name -> jeeves.engine.v1.Envelope.OutputsEntry
	16, // 6: jeeves.engine.v1.Envelope.active_stages:type_name -> jeeves.engine.v1.Envelope.ActiveStagesEntry
	17, // 7: jeeves.engine.v1.Envelope.completed_stage_set:type_name -> jeeves.engine.v1.Envelope.CompletedStageSetEntry
	18, // 8: jeeves.engine.v1.Envelope.failed_stages:type_name -> jeeves.engine.v1.Envelope.FailedStagesEntry
	19, // 9: jeeves.engine.v1.Envelope.goal_completion_status:type_name -> jeeves.engine.v1.Envelope.GoalCompletionStatusEntry
	20, // 10: jeeves.engine.v1.Envelope.metadata_str:type_name -> jeeves.engine.v1.Envelope.MetadataStrEntry
	1,  // 11: jeeves.engine.v1.FlowInterrupt.kind:type_name -> jeeves.engine.v1.InterruptKind
	8,  // 12: jeeves.engine.v1.FlowInterrupt.response:type_name -> jeeves.engine.v1.InterruptResponse
	0,  // 13: jeeves.engine.v1.BoundsResult.terminal_reason:type_name -> jeeves.engine.v1.TerminalReason
	6,  // 14: jeeves.engine.v1.ExecuteRequest.envelope:type_name -> jeeves.engine.v1.Envelope
	6,  // 15: jeeves.engine.v1.ExecuteAgentRequest.envelope:type_name -> jeeves.engine.v1.Envelope
	2,  // 16: jeeves.engine.v1.ExecutionEvent.type:type_name -> jeeves.engine.v1.ExecutionEventType
	6,  // 17: jeeves.engine.v1.ExecutionEvent.envelope:type_name -> jeeves.engine.v1.Envelope
	6,  // 18: jeeves.engine.v1.AgentResult.envelope:type_name -> jeeves.engine.v1.Envelope
	3,  // 19: jeeves.engine.v1.EngineService.CreateEnvelope:input_type -> jeeves.engine.v1.CreateEnvelopeRequest
	4,  // 20: jeeves.engine.v1.EngineService.UpdateEnvelope:input_type -> jeeves.engine.v1.UpdateEnvelopeRequest
	6,  // 21: jeeves.engine.v1.EngineService.CheckBounds:input_type -> jeeves.engine.v1.Envelope
	10, // 22: jeeves.engine.v1.EngineService.ExecutePipeline:input_type -> jeeves.engine.v1.ExecuteRequest
	11, // 23: jeeves.engine.v1.EngineService.ExecuteAgent:input_type -> jeeves.engine.v1.ExecuteAgentRequest
	5,  // 24: jeeves.engine.v1.EngineService.CloneEnvelope:input_type -> jeeves.engine.v1.CloneRequest
	6,  // 25: jeeves.engine.v1.EngineService.CreateEnvelope:output_type -> jeeves.engine.v1.Envelope
	6,  // 26: jeeves.engine.v1.EngineService.UpdateEnvelope:output_type -> jeeves.engine.v1.Envelope
	9,  // 27: jeeves.engine.v1.EngineService.CheckBounds:output_type -> jeeves.engine.v1.BoundsResult
	12, // 28: jeeves.engine.v1.EngineService.ExecutePipeline:output_type -> jeeves.engine.v1.ExecutionEvent
	13, // 29: jeeves.engine.v1.EngineService.ExecuteAgent:output_type -> jeeves.engine.v1.AgentResult
	6,  // 30: jeeves.engine.v1.EngineService.CloneEnvelope:output_type -> jeeves.engine.v1.Envelope
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_coreengine_proto_engine_proto_init() }
func file_coreengine_proto_engine_proto_init() {
	if File_coreengine_proto_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coreengine_proto_engine_proto_rawDesc), len(file_coreengine_proto_engine_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coreengine_proto_engine_proto_goTypes,
		DependencyIndexes: file_coreengine_proto_engine_proto_depIdxs,
		EnumInfos:         file_coreengine_proto_engine_proto_enumTypes,
		MessageInfos:      file_coreengine_proto_engine_proto_msgTypes,
	}.Build()
	File_coreengine_proto_engine_proto = out.File
	file_coreengine_proto_engine_proto_goTypes = nil
	file_coreengine_proto_engine_proto_depIdxs = nil
}
