# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coreengine.proto import engine_pb2 as coreengine_dot_proto_dot_engine__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coreengine/proto/engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineServiceStub(object):
    """=============================================================================
    EngineService - Go runtime operations
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEnvelope = channel.unary_unary(
                '/jeeves.engine.v1.EngineService/CreateEnvelope',
                request_serializer=coreengine_dot_proto_dot_engine__pb2.CreateEnvelopeRequest.SerializeToString,
                response_deserializer=coreengine_dot_proto_dot_engine__pb2.Envelope.FromString,
                _registered_method=True)
        self.UpdateEnvelope = channel.unary_unary(
                '/jeeves.engine.v1.EngineService/UpdateEnvelope',
                request_serializer=coreengine_dot_proto_dot_engine__pb2.UpdateEnvelopeRequest.SerializeToString,
                response_deserializer=coreengine_dot_proto_dot_engine__pb2.Envelope.FromString,
                _registered_method=True)
        self.CheckBounds = channel.unary_unary(
                '/jeeves.engine.v1.EngineService/CheckBounds',
                request_serializer=coreengine_dot_proto_dot_engine__pb2.Envelope.SerializeToString,
                response_deserializer=coreengine_dot_proto_dot_engine__pb2.BoundsResult.FromString,
                _registered_method=True)
        self.ExecutePipeline = channel.unary_stream(
                '/jeeves.engine.v1.EngineService/ExecutePipeline',
                request_serializer=coreengine_dot_proto_dot_engine__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=coreengine_dot_proto_dot_engine__pb2.ExecutionEvent.FromString,
                _registered_method=True)
        self.ExecuteAgent = channel.unary_unary(
                '/jeeves.engine.v1.EngineService/ExecuteAgent',
                request_serializer=coreengine_dot_proto_dot_engine__pb2.ExecuteAgentRequest.SerializeToString,
                response_deserializer=coreengine_dot_proto_dot_engine__pb2.AgentResult.FromString,
                _registered_method=True)
        self.CloneEnvelope = channel.unary_unary(
                '/jeeves.engine.v1.EngineService/CloneEnvelope',
                request_serializer=coreengine_dot_proto_dot_engine__pb2.CloneRequest.SerializeToString,
                response_deserializer=coreengine_dot_proto_dot_engine__pb2.Envelope.FromString,
                _registered_method=True)


class EngineServiceServicer(object):
    """=============================================================================
    EngineService - Go runtime operations
    =============================================================================
    """

    def CreateEnvelope(self, request, context):
        """Envelope lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEnvelope(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBounds(self, request, context):
        """Bounds checking (Go is authoritative)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePipeline(self, request, context):
        """Execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloneEnvelope(self, request, context):
        """State management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEnvelope': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvelope,
                    request_deserializer=coreengine_dot_proto_dot_engine__pb2.CreateEnvelopeRequest.FromString,
                    response_serializer=coreengine_dot_proto_dot_engine__pb2.Envelope.SerializeToString,
            ),
            'UpdateEnvelope': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEnvelope,
                    request_deserializer=coreengine_dot_proto_dot_engine__pb2.UpdateEnvelopeRequest.FromString,
                    response_serializer=coreengine_dot_proto_dot_engine__pb2.Envelope.SerializeToString,
            ),
            'CheckBounds': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBounds,
                    request_deserializer=coreengine_dot_proto_dot_engine__pb2.Envelope.FromString,
                    response_serializer=coreengine_dot_proto_dot_engine__pb2.BoundsResult.SerializeToString,
            ),
            'ExecutePipeline': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecutePipeline,
                    request_deserializer=coreengine_dot_proto_dot_engine__pb2.ExecuteRequest.FromString,
                    response_serializer=coreengine_dot_proto_dot_engine__pb2.ExecutionEvent.SerializeToString,
            ),
            'ExecuteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAgent,
                    request_deserializer=coreengine_dot_proto_dot_engine__pb2.ExecuteAgentRequest.FromString,
                    response_serializer=coreengine_dot_proto_dot_engine__pb2.AgentResult.SerializeToString,
            ),
            'CloneEnvelope': grpc.unary_unary_rpc_method_handler(
                    servicer.CloneEnvelope,
                    request_deserializer=coreengine_dot_proto_dot_engine__pb2.CloneRequest.FromString,
                    response_serializer=coreengine_dot_proto_dot_engine__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jeeves.engine.v1.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jeeves.engine.v1.EngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """=============================================================================
    EngineService - Go runtime operations
    =============================================================================
    """

    @staticmethod
    def CreateEnvelope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.engine.v1.EngineService/CreateEnvelope',
            coreengine_dot_proto_dot_engine__pb2.CreateEnvelopeRequest.SerializeToString,
            coreengine_dot_proto_dot_engine__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEnvelope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.engine.v1.EngineService/UpdateEnvelope',
            coreengine_dot_proto_dot_engine__pb2.UpdateEnvelopeRequest.SerializeToString,
            coreengine_dot_proto_dot_engine__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.engine.v1.EngineService/CheckBounds',
            coreengine_dot_proto_dot_engine__pb2.Envelope.SerializeToString,
            coreengine_dot_proto_dot_engine__pb2.BoundsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jeeves.engine.v1.EngineService/ExecutePipeline',
            coreengine_dot_proto_dot_engine__pb2.ExecuteRequest.SerializeToString,
            coreengine_dot_proto_dot_engine__pb2.ExecutionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.engine.v1.EngineService/ExecuteAgent',
            coreengine_dot_proto_dot_engine__pb2.ExecuteAgentRequest.SerializeToString,
            coreengine_dot_proto_dot_engine__pb2.AgentResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloneEnvelope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jeeves.engine.v1.EngineService/CloneEnvelope',
            coreengine_dot_proto_dot_engine__pb2.CloneRequest.SerializeToString,
            coreengine_dot_proto_dot_engine__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
