// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub implementation for development.
// Run protoc to generate the real implementation.

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// TerminalReason enum
type TerminalReason int32

const (
	TerminalReason_TERMINAL_REASON_UNSPECIFIED TerminalReason = 0
	TerminalReason_MAX_ITERATIONS_EXCEEDED     TerminalReason = 1
	TerminalReason_MAX_LLM_CALLS_EXCEEDED      TerminalReason = 2
	TerminalReason_MAX_AGENT_HOPS_EXCEEDED     TerminalReason = 3
	TerminalReason_USER_CANCELLED              TerminalReason = 4
	TerminalReason_TOOL_FAILED_FATALLY         TerminalReason = 5
	TerminalReason_LLM_FAILED_FATALLY          TerminalReason = 6
	TerminalReason_COMPLETED                   TerminalReason = 7
)

// InterruptKind enum
type InterruptKind int32

const (
	InterruptKind_INTERRUPT_KIND_UNSPECIFIED InterruptKind = 0
	InterruptKind_CLARIFICATION              InterruptKind = 1
	InterruptKind_CONFIRMATION               InterruptKind = 2
	InterruptKind_CHECKPOINT                 InterruptKind = 3
	InterruptKind_RESOURCE_EXHAUSTED         InterruptKind = 4
	InterruptKind_TIMEOUT                    InterruptKind = 5
	InterruptKind_SYSTEM_ERROR               InterruptKind = 6
	InterruptKind_AGENT_REVIEW               InterruptKind = 7
)

// ExecutionEventType enum
type ExecutionEventType int32

const (
	ExecutionEventType_EXECUTION_EVENT_TYPE_UNSPECIFIED ExecutionEventType = 0
	ExecutionEventType_STAGE_STARTED                    ExecutionEventType = 1
	ExecutionEventType_STAGE_COMPLETED                  ExecutionEventType = 2
	ExecutionEventType_STAGE_FAILED                     ExecutionEventType = 3
	ExecutionEventType_PIPELINE_COMPLETED               ExecutionEventType = 4
	ExecutionEventType_INTERRUPT_RAISED                 ExecutionEventType = 5
	ExecutionEventType_CHECKPOINT_CREATED               ExecutionEventType = 6
	ExecutionEventType_BOUNDS_EXCEEDED                  ExecutionEventType = 7
)

// CreateEnvelopeRequest message
type CreateEnvelopeRequest struct {
	RawInput   string            `json:"raw_input"`
	UserId     string            `json:"user_id"`
	SessionId  string            `json:"session_id"`
	RequestId  string            `json:"request_id"`
	Metadata   map[string]string `json:"metadata"`
	StageOrder []string          `json:"stage_order"`
}

// UpdateEnvelopeRequest message
type UpdateEnvelopeRequest struct {
	Envelope *Envelope `json:"envelope"`
}

// CloneRequest message
type CloneRequest struct {
	Envelope *Envelope `json:"envelope"`
}

// Envelope message
type Envelope struct {
	EnvelopeId           string            `json:"envelope_id"`
	RequestId            string            `json:"request_id"`
	UserId               string            `json:"user_id"`
	SessionId            string            `json:"session_id"`
	RawInput             string            `json:"raw_input"`
	ReceivedAtMs         int64             `json:"received_at_ms"`
	CurrentStage         string            `json:"current_stage"`
	StageOrder           []string          `json:"stage_order"`
	Iteration            int32             `json:"iteration"`
	MaxIterations        int32             `json:"max_iterations"`
	LlmCallCount         int32             `json:"llm_call_count"`
	MaxLlmCalls          int32             `json:"max_llm_calls"`
	AgentHopCount        int32             `json:"agent_hop_count"`
	MaxAgentHops         int32             `json:"max_agent_hops"`
	Terminated           bool              `json:"terminated"`
	TerminationReason    string            `json:"termination_reason"`
	TerminalReason       TerminalReason    `json:"terminal_reason"`
	CompletedAtMs        int64             `json:"completed_at_ms"`
	InterruptPending     bool              `json:"interrupt_pending"`
	Interrupt            *FlowInterrupt    `json:"interrupt"`
	Outputs              map[string][]byte `json:"outputs"`
	ActiveStages         map[string]bool   `json:"active_stages"`
	CompletedStageSet    map[string]bool   `json:"completed_stage_set"`
	FailedStages         map[string]string `json:"failed_stages"`
	CurrentStageNumber   int32             `json:"current_stage_number"`
	MaxStages            int32             `json:"max_stages"`
	AllGoals             []string          `json:"all_goals"`
	RemainingGoals       []string          `json:"remaining_goals"`
	GoalCompletionStatus map[string]string `json:"goal_completion_status"`
	MetadataStr          map[string]string `json:"metadata_str"`
	CreatedAtMs          int64             `json:"created_at_ms"`
}

// FlowInterrupt message
type FlowInterrupt struct {
	Kind        InterruptKind      `json:"kind"`
	InterruptId string             `json:"interrupt_id"`
	Question    string             `json:"question"`
	Message     string             `json:"message"`
	Data        []byte             `json:"data"`
	Response    *InterruptResponse `json:"response"`
	CreatedAtMs int64              `json:"created_at_ms"`
}

// InterruptResponse message
type InterruptResponse struct {
	Text         string `json:"text"`
	Approved     bool   `json:"approved"`
	Decision     string `json:"decision"`
	Data         []byte `json:"data"`
	ResolvedAtMs int64  `json:"resolved_at_ms"`
}

// BoundsResult message
type BoundsResult struct {
	CanContinue         bool           `json:"can_continue"`
	TerminalReason      TerminalReason `json:"terminal_reason"`
	LlmCallsRemaining   int32          `json:"llm_calls_remaining"`
	AgentHopsRemaining  int32          `json:"agent_hops_remaining"`
	IterationsRemaining int32          `json:"iterations_remaining"`
}

// ExecuteRequest message
type ExecuteRequest struct {
	Envelope       *Envelope `json:"envelope"`
	ThreadId       string    `json:"thread_id"`
	PipelineConfig []byte    `json:"pipeline_config"`
}

// ExecuteAgentRequest message
type ExecuteAgentRequest struct {
	Envelope    *Envelope `json:"envelope"`
	AgentName   string    `json:"agent_name"`
	AgentConfig []byte    `json:"agent_config"`
}

// ExecutionEvent message
type ExecutionEvent struct {
	Type        ExecutionEventType `json:"type"`
	Stage       string             `json:"stage"`
	TimestampMs int64              `json:"timestamp_ms"`
	Payload     []byte             `json:"payload"`
	Envelope    *Envelope          `json:"envelope"`
}

// AgentResult message
type AgentResult struct {
	Success    bool      `json:"success"`
	Output     []byte    `json:"output"`
	Error      string    `json:"error"`
	DurationMs int32     `json:"duration_ms"`
	LlmCalls   int32     `json:"llm_calls"`
	Envelope   *Envelope `json:"envelope"`
}

// JeevesCoreServiceClient interface
type JeevesCoreServiceClient interface {
	CreateEnvelope(ctx context.Context, in *CreateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error)
	UpdateEnvelope(ctx context.Context, in *UpdateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error)
	CheckBounds(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*BoundsResult, error)
	ExecutePipeline(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (JeevesCoreService_ExecutePipelineClient, error)
	ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (*AgentResult, error)
	CloneEnvelope(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*Envelope, error)
}

// JeevesCoreService_ExecutePipelineClient interface
type JeevesCoreService_ExecutePipelineClient interface {
	Recv() (*ExecutionEvent, error)
	grpc.ClientStream
}

// JeevesCoreServiceServer interface
type JeevesCoreServiceServer interface {
	CreateEnvelope(context.Context, *CreateEnvelopeRequest) (*Envelope, error)
	UpdateEnvelope(context.Context, *UpdateEnvelopeRequest) (*Envelope, error)
	CheckBounds(context.Context, *Envelope) (*BoundsResult, error)
	ExecutePipeline(*ExecuteRequest, JeevesCoreService_ExecutePipelineServer) error
	ExecuteAgent(context.Context, *ExecuteAgentRequest) (*AgentResult, error)
	CloneEnvelope(context.Context, *CloneRequest) (*Envelope, error)
	mustEmbedUnimplementedJeevesCoreServiceServer()
}

// JeevesCoreService_ExecutePipelineServer interface
type JeevesCoreService_ExecutePipelineServer interface {
	Send(*ExecutionEvent) error
	grpc.ServerStream
}

// UnimplementedJeevesCoreServiceServer for forward compatibility
type UnimplementedJeevesCoreServiceServer struct{}

func (UnimplementedJeevesCoreServiceServer) CreateEnvelope(context.Context, *CreateEnvelopeRequest) (*Envelope, error) {
	return nil, nil
}
func (UnimplementedJeevesCoreServiceServer) UpdateEnvelope(context.Context, *UpdateEnvelopeRequest) (*Envelope, error) {
	return nil, nil
}
func (UnimplementedJeevesCoreServiceServer) CheckBounds(context.Context, *Envelope) (*BoundsResult, error) {
	return nil, nil
}
func (UnimplementedJeevesCoreServiceServer) ExecutePipeline(*ExecuteRequest, JeevesCoreService_ExecutePipelineServer) error {
	return nil
}
func (UnimplementedJeevesCoreServiceServer) ExecuteAgent(context.Context, *ExecuteAgentRequest) (*AgentResult, error) {
	return nil, nil
}
func (UnimplementedJeevesCoreServiceServer) CloneEnvelope(context.Context, *CloneRequest) (*Envelope, error) {
	return nil, nil
}
func (UnimplementedJeevesCoreServiceServer) mustEmbedUnimplementedJeevesCoreServiceServer() {}

// RegisterJeevesCoreServiceServer registers the server
func RegisterJeevesCoreServiceServer(s grpc.ServiceRegistrar, srv JeevesCoreServiceServer) {
	// This is a stub - real implementation generated by protoc
}

