// Jeeves Core gRPC Service - Python <-> Go runtime bridge
//
// This is the primary IPC mechanism between Python orchestration
// and Go execution engine. Replaces subprocess-based JSON IPC.
//
// Compile Go:
//   protoc --go_out=. --go-grpc_out=. coreengine/proto/jeeves_core.proto
//
// Compile Python:
//   python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. coreengine/proto/jeeves_core.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: jeeves_core.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JeevesCoreService_CreateEnvelope_FullMethodName  = "/jeeves.core.v1.JeevesCoreService/CreateEnvelope"
	JeevesCoreService_UpdateEnvelope_FullMethodName  = "/jeeves.core.v1.JeevesCoreService/UpdateEnvelope"
	JeevesCoreService_CheckBounds_FullMethodName     = "/jeeves.core.v1.JeevesCoreService/CheckBounds"
	JeevesCoreService_ExecutePipeline_FullMethodName = "/jeeves.core.v1.JeevesCoreService/ExecutePipeline"
	JeevesCoreService_ExecuteAgent_FullMethodName    = "/jeeves.core.v1.JeevesCoreService/ExecuteAgent"
	JeevesCoreService_CloneEnvelope_FullMethodName   = "/jeeves.core.v1.JeevesCoreService/CloneEnvelope"
)

// JeevesCoreServiceClient is the client API for JeevesCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// JeevesCoreService - Go runtime operations
// =============================================================================
type JeevesCoreServiceClient interface {
	// Envelope lifecycle
	CreateEnvelope(ctx context.Context, in *CreateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error)
	UpdateEnvelope(ctx context.Context, in *UpdateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error)
	// Bounds checking (Go is authoritative)
	CheckBounds(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*BoundsResult, error)
	// Execution
	ExecutePipeline(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionEvent], error)
	ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (*AgentResult, error)
	// State management
	CloneEnvelope(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*Envelope, error)
}

type jeevesCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJeevesCoreServiceClient(cc grpc.ClientConnInterface) JeevesCoreServiceClient {
	return &jeevesCoreServiceClient{cc}
}

func (c *jeevesCoreServiceClient) CreateEnvelope(ctx context.Context, in *CreateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, JeevesCoreService_CreateEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jeevesCoreServiceClient) UpdateEnvelope(ctx context.Context, in *UpdateEnvelopeRequest, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, JeevesCoreService_UpdateEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jeevesCoreServiceClient) CheckBounds(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*BoundsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoundsResult)
	err := c.cc.Invoke(ctx, JeevesCoreService_CheckBounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jeevesCoreServiceClient) ExecutePipeline(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JeevesCoreService_ServiceDesc.Streams[0], JeevesCoreService_ExecutePipeline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecutionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JeevesCoreService_ExecutePipelineClient = grpc.ServerStreamingClient[ExecutionEvent]

func (c *jeevesCoreServiceClient) ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (*AgentResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResult)
	err := c.cc.Invoke(ctx, JeevesCoreService_ExecuteAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jeevesCoreServiceClient) CloneEnvelope(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, JeevesCoreService_CloneEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JeevesCoreServiceServer is the server API for JeevesCoreService service.
// All implementations must embed UnimplementedJeevesCoreServiceServer
// for forward compatibility.
//
// =============================================================================
// JeevesCoreService - Go runtime operations
// =============================================================================
type JeevesCoreServiceServer interface {
	// Envelope lifecycle
	CreateEnvelope(context.Context, *CreateEnvelopeRequest) (*Envelope, error)
	UpdateEnvelope(context.Context, *UpdateEnvelopeRequest) (*Envelope, error)
	// Bounds checking (Go is authoritative)
	CheckBounds(context.Context, *Envelope) (*BoundsResult, error)
	// Execution
	ExecutePipeline(*ExecuteRequest, grpc.ServerStreamingServer[ExecutionEvent]) error
	ExecuteAgent(context.Context, *ExecuteAgentRequest) (*AgentResult, error)
	// State management
	CloneEnvelope(context.Context, *CloneRequest) (*Envelope, error)
	mustEmbedUnimplementedJeevesCoreServiceServer()
}

// UnimplementedJeevesCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJeevesCoreServiceServer struct{}

func (UnimplementedJeevesCoreServiceServer) CreateEnvelope(context.Context, *CreateEnvelopeRequest) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnvelope not implemented")
}
func (UnimplementedJeevesCoreServiceServer) UpdateEnvelope(context.Context, *UpdateEnvelopeRequest) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnvelope not implemented")
}
func (UnimplementedJeevesCoreServiceServer) CheckBounds(context.Context, *Envelope) (*BoundsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBounds not implemented")
}
func (UnimplementedJeevesCoreServiceServer) ExecutePipeline(*ExecuteRequest, grpc.ServerStreamingServer[ExecutionEvent]) error {
	return status.Error(codes.Unimplemented, "method ExecutePipeline not implemented")
}
func (UnimplementedJeevesCoreServiceServer) ExecuteAgent(context.Context, *ExecuteAgentRequest) (*AgentResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAgent not implemented")
}
func (UnimplementedJeevesCoreServiceServer) CloneEnvelope(context.Context, *CloneRequest) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method CloneEnvelope not implemented")
}
func (UnimplementedJeevesCoreServiceServer) mustEmbedUnimplementedJeevesCoreServiceServer() {}
func (UnimplementedJeevesCoreServiceServer) testEmbeddedByValue()                           {}

// UnsafeJeevesCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JeevesCoreServiceServer will
// result in compilation errors.
type UnsafeJeevesCoreServiceServer interface {
	mustEmbedUnimplementedJeevesCoreServiceServer()
}

func RegisterJeevesCoreServiceServer(s grpc.ServiceRegistrar, srv JeevesCoreServiceServer) {
	// If the following call panics, it indicates UnimplementedJeevesCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JeevesCoreService_ServiceDesc, srv)
}

func _JeevesCoreService_CreateEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JeevesCoreServiceServer).CreateEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JeevesCoreService_CreateEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JeevesCoreServiceServer).CreateEnvelope(ctx, req.(*CreateEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JeevesCoreService_UpdateEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JeevesCoreServiceServer).UpdateEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JeevesCoreService_UpdateEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JeevesCoreServiceServer).UpdateEnvelope(ctx, req.(*UpdateEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JeevesCoreService_CheckBounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JeevesCoreServiceServer).CheckBounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JeevesCoreService_CheckBounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JeevesCoreServiceServer).CheckBounds(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _JeevesCoreService_ExecutePipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JeevesCoreServiceServer).ExecutePipeline(m, &grpc.GenericServerStream[ExecuteRequest, ExecutionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JeevesCoreService_ExecutePipelineServer = grpc.ServerStreamingServer[ExecutionEvent]

func _JeevesCoreService_ExecuteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JeevesCoreServiceServer).ExecuteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JeevesCoreService_ExecuteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JeevesCoreServiceServer).ExecuteAgent(ctx, req.(*ExecuteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JeevesCoreService_CloneEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JeevesCoreServiceServer).CloneEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JeevesCoreService_CloneEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JeevesCoreServiceServer).CloneEnvelope(ctx, req.(*CloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JeevesCoreService_ServiceDesc is the grpc.ServiceDesc for JeevesCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JeevesCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jeeves.core.v1.JeevesCoreService",
	HandlerType: (*JeevesCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEnvelope",
			Handler:    _JeevesCoreService_CreateEnvelope_Handler,
		},
		{
			MethodName: "UpdateEnvelope",
			Handler:    _JeevesCoreService_UpdateEnvelope_Handler,
		},
		{
			MethodName: "CheckBounds",
			Handler:    _JeevesCoreService_CheckBounds_Handler,
		},
		{
			MethodName: "ExecuteAgent",
			Handler:    _JeevesCoreService_ExecuteAgent_Handler,
		},
		{
			MethodName: "CloneEnvelope",
			Handler:    _JeevesCoreService_CloneEnvelope_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecutePipeline",
			Handler:       _JeevesCoreService_ExecutePipeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jeeves_core.proto",
}
